module.exports = {
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
  SIGN_OUT: 'SIGN_OUT',
  ACTIVATE_TAG: 'ACTIVATE_TAG',
  DEACTIVATE_TAG: 'DEACTIVATE_TAG',
  SET_ACTIVE_TAGS: 'SET_ACTIVE_TAGS',
  FETCH_TAGS_SUCCESS: 'FETCH_TAGS_SUCCESS',
  FETCH_TAGS_FAILURE: 'FETCH_TAGS_FAILURE'
}