module.exports = {
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
  SIGN_OUT: 'SIGN_OUT',
  ACTIVATE_TAG: 'ACTIVATE_TAG',
  DEACTIVATE_TAG: 'DEACTIVATE_TAG',
  SET_ACTIVE_TAGS: 'SET_ACTIVE_TAGS',
  FETCH_TAGS_SUCCESS: 'FETCH_TAGS_SUCCESS',
  FETCH_TAGS_FAILURE: 'FETCH_TAGS_FAILURE',
  CREATE_TODO: 'CREATE_TODO_SUCCESS',
  CREATE_TODO: 'CREATE_TODO_FAILURE',
  UPDATE_TODO: 'UPDATE_TODO_SUCCESS',
  UPDATE_TODO: 'UPDATE_TODO_FAILURE',
  REMOVE_TODO: 'REMOVE_TODO_SUCCESS',
  REMOVE_TODO: 'REMOVE_TODO_FAILURE'
}
